all:
  vars:
    ansible_network_os: ios
    ansible_ssh_user: ec2-user
    ansible_ssh_private_key_file: provisioner/{{ lookup('env', 'SSH_KEY_FILE') }}
  children:
    site1:
      children:
        tag_location_site1:

    site2:
      children:
        tag_location_site2:
